#!/bin/bash
set -eux

if [ $# -eq 1 ]
  then
    cd $1
fi

working_dir=$(pwd)

if [ -f "Pipfile.lock" ]; then
    dependencies='Pipfile.lock'
else
    dependencies='requirements.txt'
fi


rm -rf build
mkdir -p build

if [ -f "Pipfile.lock" ]; then
    PIPENV_TIMEOUT=600 pipenv install --ignore-pipfile
    site_packages=$(pipenv run python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
    mv "${site_packages}" build/deployment
    pipenv --rm
else
    virtual_env_dir="build/virtualenv"
    mkdir -p ${virtual_env_dir}
    export VIRTUAL_ENV_DISABLE_PROMPT=true

    virtualenv "$virtual_env_dir"
    source "$virtual_env_dir"/bin/activate

    python -m pip install --no-cache-dir -r requirements.txt
    site_packages="$virtual_env_dir"/lib/python2.7/site-packages
    mv "${site_packages}" build/deployment
    rm -r "$virtual_env_dir"
fi

if [ -f "setup.py" ]; then
    python setup.py sdist
    python -m pip install dist/* -t build/deployment/
    rm -rf dist
    rm -rf *.egg-info
else
    cp -r src/* build/deployment/
fi

cd build/deployment;

zip -X -r ../lambda.zip *  -x "*.pyc"

cd ../../; rm -r build/deployment ;

echo "ZIP_LOCATION=$working_dir/build/lambda.zip"
