#!/bin/bash
set -eux

VERSION=7.0.8-14
CHECKOUT_DIR=ImageMagick-${VERSION}

cd /tmp

wget -O ${CHECKOUT_DIR}.tar.gz https://github.com/ImageMagick/ImageMagick/archive/${VERSION}.tar.gz

tar xvzf ${CHECKOUT_DIR}.tar.gz
cd ${CHECKOUT_DIR}
./configure
make
sudo make install

# You may need to configure the dynamic linker run-time bindings:
sudo ldconfig /usr/local/lib

# Print version
identify -version

# clean-up
rm -rf ${CHECKOUT_DIR}
rm -rf ${CHECKOUT_DIR}.tar.gz
